spring.application.name=rutau



# Conexión mediante Supabase Pooler (Región us-east-1 - Puerto IPv4 6543)
spring.datasource.url=jdbc:postgresql://aws-0-us-east-1.pooler.supabase.com:6543/postgres?sslmode=require
spring.datasource.username=postgres.rnfubcdphcoouxfgwivc
spring.datasource.password=fGK2PN2WUncM5BkR
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true